        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 21 15:03:11 2011
        MODULE ADDQUOTE__genmod
          INTERFACE 
            SUBROUTINE ADDQUOTE(AFILE,AQFILE)
              CHARACTER(*), INTENT(IN) :: AFILE
              CHARACTER(*), INTENT(OUT) :: AQFILE
            END SUBROUTINE ADDQUOTE
          END INTERFACE 
        END MODULE ADDQUOTE__genmod
